---
#- hosts: localhost

#  collections:
#    - cyberark.pas

#  tasks:
    - name: Logon to CyberArk Vault
      cyberark_authentication:
        api_base_url: "{{ CYBERARK_API_URL }}"
        validate_certs: no
        username: "{{ CYBERARK_API_USERNAME }}"
        password: "{{ CYBERARK_API_USERNAME }}"

    - name: Debug message
      debug:
        var: cyberark_session

    - name: Creating a CyberArk User, setting a simple password but forcing a password change at next logon
      cyberark_user:
        username: "{{ CYBERARK_AUTH_USERNAME }}"
        first_name: "{{ CYBERARK_AUTH_FIRSTN }}"
        last_name: "{{ CYBERARK_AUTH_LASTN }}"
        email: "{{ CYBERARK_AUTH_EMAIL }}"
        initial_password: "{{ CYBERARK_AUTH_INTIT_PW }}"
        user_type_name: "{{ CYBERARK_AUTH_USER_TYPE }}"
        group_name: "{{ CYBERARK_AUTH_GROUP_NAME }}"
        disabled: false
        state: present
        cyberark_session: "{{ cyberark_session }}"
      register: cyberarkaction

    - name: Debug message
      debug:
        var: cyberarkaction

    - name: Logoff from CyberArk Vault
      cyberark_authentication:
        state: absent
        cyberark_session: "{{ cyberark_session }}"
